apiVersion: v1
kind: Service
metadata:
  name: tf-serving-service
  namespace: default
  labels:
    app: tf-serving
spec:
  type: NodePort
  ports:
  - port: 8501
    targetPort: 8501
    nodePort: 30001
    protocol: TCP
    name: tf-serving-http
  selector:
    app: tf-serving